name: openage-template # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: OpenAge
summary: Unveil Ancient Mysteries, Build Civilizations, and Shape History # 79 char long summary
description: |
  Unveil ancient mysteries, build thriving civilizations from humble beginnings, and lead your people through eras of innovation and conflict. 
  Strategize, explore, and conquer as you navigate the complexities of diplomacy, trade, and warfare. 

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  openage-template:
    command: bin/openage-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  openage-template:
    plugin: dump
    source: .
    organize:
      openage-bin: bin/
